http_path = "/"
css_dir = "styles/css"
sass_dir = "styles/scss"
images_dir = "images"
javascripts_dir = "js"
output_style = :nested
environment = :development
relative_assets = true
output_style = :nested # by Compass.app 